// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hl.netty._12grpcStreamBoth;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.hl.netty._12grpcStreamBoth.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.hl.netty._12grpcStreamBoth.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.hl.netty._12grpcStreamBoth.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.hl.netty._12grpcStreamBoth.StudentResponse studentResponse = 1;</code>
   */
  com.hl.netty._12grpcStreamBoth.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.hl.netty._12grpcStreamBoth.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.hl.netty._12grpcStreamBoth.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.hl.netty._12grpcStreamBoth.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.hl.netty._12grpcStreamBoth.StudentResponse studentResponse = 1;</code>
   */
  com.hl.netty._12grpcStreamBoth.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
