// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.hl.netty._11grpcRequestStream;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hl_netty__11grpcRequestStream_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hl_netty__11grpcRequestStream_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hl_netty__11grpcRequestStream_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hl_netty__11grpcRequestStream_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hl_netty__11grpcRequestStream_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hl_netty__11grpcRequestStream_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hl_netty__11grpcRequestStream_StudentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponseList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hl_netty__11grpcRequestStream_StudentResponseList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022!com.hl.netty._11grpcReq" +
      "uestStream\"\035\n\tMyRequest\022\020\n\010username\030\001 \001(" +
      "\t\"\036\n\nMyResponse\022\020\n\010realname\030\002 \001(\t\"\035\n\016Stu" +
      "dentRequest\022\013\n\003age\030\001 \001(\005\":\n\017StudentRespo" +
      "nse\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\014\n\004city\030\003" +
      " \001(\t\"b\n\023StudentResponseList\022K\n\017studentRe" +
      "sponse\030\001 \003(\01322.com.hl.netty._11grpcReque" +
      "stStream.StudentResponse2\224\003\n\016StudentServ" +
      "ice\022v\n\025GetRealNameByUserName\022,.com.hl.ne" +
      "tty._11grpcRequestStream.MyRequest\032-.com",
      ".hl.netty._11grpcRequestStream.MyRespons" +
      "e\"\000\022}\n\020GetStudentsByAge\0221.com.hl.netty._" +
      "11grpcRequestStream.StudentRequest\0322.com" +
      ".hl.netty._11grpcRequestStream.StudentRe" +
      "sponse\"\0000\001\022\212\001\n\027GetStudentsWrapperByAge\0221" +
      ".com.hl.netty._11grpcRequestStream.Stude" +
      "ntRequest\0326.com.hl.netty._11grpcRequestS" +
      "tream.StudentResponseList\"\000(\0010\001B3\n!com.h" +
      "l.netty._11grpcRequestStreamB\014StudentPro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hl_netty__11grpcRequestStream_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hl_netty__11grpcRequestStream_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hl_netty__11grpcRequestStream_MyRequest_descriptor,
        new String[] { "Username", });
    internal_static_com_hl_netty__11grpcRequestStream_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hl_netty__11grpcRequestStream_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hl_netty__11grpcRequestStream_MyResponse_descriptor,
        new String[] { "Realname", });
    internal_static_com_hl_netty__11grpcRequestStream_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_hl_netty__11grpcRequestStream_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hl_netty__11grpcRequestStream_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hl_netty__11grpcRequestStream_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponseList_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_hl_netty__11grpcRequestStream_StudentResponseList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hl_netty__11grpcRequestStream_StudentResponseList_descriptor,
        new String[] { "StudentResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
